import type { Metadata } from "next";
import { Geist_Mono, Poppins } from "next/font/google";
import { Sidebar } from "@/components/Sidebar";
import "./globals.css";
import { Toaster } from "sonner";
import { Mail, Bell, User } from "lucide-react";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${geistMono.variable} font-sans antialiased`} style={{ fontFamily: 'var(--font-poppins), sans-serif' }}>
        <div className="min-h-screen flex flex-col bg-background text-foreground">
          {/* Top nav */}
          <header className="flex items-center px-6 py-4 border-b border-border bg-white/80 sticky top-0 z-10">
            <div className="font-bold text-xl mr-8 flex items-center gap-2">
              <span className="rounded-full bg-blue-500 text-white w-8 h-8 flex items-center justify-center text-lg">F</span>
              Marketplace
            </div>
            {/* Header icons */}
            <div className="flex-1" />
            <div className="flex items-center gap-6 ml-8">
              {/* Mail icon */}
              <span className="text-gray-700 hover:text-blue-600 cursor-pointer">
                <Mail size={24} />
              </span>
              {/* Bell icon */}
              <span className="text-gray-700 hover:text-blue-600 cursor-pointer">
                <Bell size={24} />
              </span>
              {/* User icon */}
              <span className="text-gray-700 hover:text-blue-600 cursor-pointer">
                <User size={24} />
              </span>
            </div>
          </header>
          <div className="flex flex-1">
            <Sidebar />
            {/* Main content */}
            <main className="flex-1 p-6">
              {children}
            </main>
          </div>
        </div>
        <Toaster position="top-right" closeButton richColors />
      </body>
    </html>
  );
}
